In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [5]:
df.dropna(inplace=True)
## dropping nulll values
df.drop_duplicates(inplace=True)
## dropping duplicate values

In [7]:
df["id"]=df["id"].astype(str)
df["host_id"]=df["host_id"].astype(str)
df["latitude"]=df["latitude"].astype(str)
df["longitude"]=df["longitude"].astype(str)

In [9]:
df.describe()

,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,38821.000000,38821.000000,38821.000000,38821.000000,38821.000000,38821.000000
mean,142.332526,5.869220,29.290255,1.373229,5.166611,114.886299
std,196.994756,17.389026,48.182900,1.680328,26.302954,129.529950
min,0.000000,1.000000,1.000000,0.010000,1.000000,0.000000
25%,69.000000,1.000000,3.000000,0.190000,1.000000,0.000000
50%,101.000000,2.000000,9.000000,0.720000,1.000000,55.000000
75%,170.000000,4.000000,33.000000,2.020000,2.000000,229.000000
max,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [11]:
df.nunique()

id                                38821
name                              38253
host_id                           30232
host_name                          9885
neighbourhood_group                   5
neighbourhood                       218
latitude                          17436
longitude                         13639
room_type                             3
price                               581
minimum_nights                       89
number_of_reviews                   393
last_review                        1764
reviews_per_month                   937
calculated_host_listings_count       47
availability_365                    366
dtype: int64

## Categorical

In [13]:
df["neighbourhood_group"].value_counts()

neighbourhood_group
Manhattan        16621
Brooklyn         16439
Queens            4572
Bronx              875
Staten Island      314
Name: count, dtype: int64

In [15]:
df["neighbourhood_group"].value_counts(normalize=True)

neighbourhood_group
Manhattan        0.428145
Brooklyn         0.423456
Queens           0.117771
Bronx            0.022539
Staten Island    0.008088
Name: proportion, dtype: float64

In [17]:
df["neighbourhood_group"].value_counts().reset_index()

  neighbourhood_group  count
0           Manhattan  16621
1            Brooklyn  16439
2              Queens   4572
3               Bronx    875
4       Staten Island    314

In [25]:
df_n=df["neighbourhood_group"].value_counts().reset_index().rename(columns ={"count": "No. of hotels"})
df_n

  neighbourhood_group  No. of hotels
0           Manhattan          16621
1            Brooklyn          16439
2              Queens           4572
3               Bronx            875
4       Staten Island            314

In [31]:
df_n[df_n["No. of hotels"]>1000]

  neighbourhood_group  No. of hotels
0           Manhattan          16621
1            Brooklyn          16439
2              Queens           4572

## Numerical

In [35]:
df["price"].value_counts(bins=5)
## means it divides the whole price into 5 equal intervals

(-10.001, 2000.0]    38786
(2000.0, 4000.0]        20
(4000.0, 6000.0]         8
(8000.0, 10000.0]        5
(6000.0, 8000.0]         2
Name: count, dtype: int64

In [37]:
bins=(0,50,100,200,500,2000,10000)

In [39]:
df["price"].value_counts(bins=bins)
## will get breakage of hotesls in these prices as well

(50.0, 100.0]        14212
(100.0, 200.0]       13544
(200.0, 500.0]        5267
(-0.001, 50.0]        5176
(500.0, 2000.0]        587
(2000.0, 10000.0]       35
Name: count, dtype: int64

In [41]:
df["price"].mean()

142.33252621004095

In [43]:
df["price"].std()

196.99475591833985

In [45]:
df["price"].skew()

23.673594295123014

In [47]:
df["price"].kurt()
## gives height of the graph

953.4807356344944

In [49]:
df.corr()
## correlation lies b/w -1 to 1 if it is 0 means they r not correlated
## shows if any reltion b/w any 2 columns

ValueError: could not convert string to float: 'Clean & quiet apt home by the park'